Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "db/schema.rb"
